FROM itzg/minecraft-server:java21-jdk

USER root

RUN apt-get update && \
    apt-get install -y libxtst6 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER minecraft

ENV JAVA_TOOL_OPTIONS -Djava.awt.headless=true